apiVersion: batch/v1
kind: Job
metadata:
  name: mssql-init
  namespace: relibank
  labels:
    app: mssql-init
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: mssql-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mssql-init
        image: mssql-custom:latest
        imagePullPolicy: Never
        command: ["/bin/bash"]
        args: ["-c", "echo 'Waiting for MSSQL server to be ready...' && sleep 45 && echo 'Connecting to MSSQL server...' && /opt/mssql-tools18/bin/sqlcmd -S mssql,1433 -U SA -P \"$MSSQL_SA_PASSWORD\" -C -i /usr/config/init.sql && echo 'Database initialization completed successfully'"]
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: MSSQL_SA_PASSWORD
