apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: relibank
  labels:
    app: mssql
spec:
  type: ClusterIP  # Regular ClusterIP service instead of headless
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
    name: tcpsql
