apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: relibank
  labels:
    app: postgres-init
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: postgres-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: postgres-init
        image: postgres-custom
        imagePullPolicy: Never
        command: ["/bin/bash"]
        args: ["-c", "echo 'Waiting for PostgreSQL server to be ready...' && sleep 30 && echo 'Connecting to PostgreSQL server...' && PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_SERVER_NAME -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DATABASE_NAME -f /usr/config/init.sql && echo 'Database initialization completed successfully'"]
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: accounts-db-credentials
              key: password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_USER
        - name: POSTGRES_SERVER_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_SERVER_NAME
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_PORT
        - name: POSTGRES_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: POSTGRES_DATABASE_NAME
