apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
  name: mssql-data
  namespace: relibank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
