kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageAccountType: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mssql-data
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
  name: mssql-data
  namespace: relibank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
