apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: relibank
  labels:
    app: accounts-db
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
