services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_MY_ID=1

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFD_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,EXTERNAL://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  mssql:
    build:
      context: ./transaction_service/mssql
      dockerfile: Dockerfile
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=YourStrong@Password!
      - ACCEPT_EULA=Y
    platform: linux/amd64
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P \"YourStrong@Password!\" -Q \"SELECT 1 FROM sys.databases WHERE name='RelibankDB'\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssql-data:/var/opt/mssql

  mssql-init:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    container_name: mssql-init
    platform: linux/amd64
    depends_on:
      mssql:
        condition: service_healthy
    command: /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P "YourStrong@Password!" -i /usr/config/init.sql
    volumes:
      - ./transaction_service/mssql/init.sql:/usr/config/init.sql

  bill-pay:
    build:
      context: ./bill_pay
    container_name: bill-pay
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:29092

  transaction-service:
    build:
      context: ./transaction_service
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "5001:5000"
    depends_on:
      kafka:
        condition: service_healthy
      mssql-init:
        condition: service_completed_successfully
    command: ["sh", "-c", "sleep 30s && uvicorn transaction_service:app --host 0.0.0.0 --port 5000 --workers 1"]
    environment:
      KAFKA_BROKER: kafka:29092
      DB_SERVER: mssql
      DB_DATABASE: RelibankDB
      DB_USERNAME: SA
      DB_PASSWORD: YourStrong@Password!

volumes:
  mssql-data:
