apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: relibank
build:
  # Build configuration for all services
  artifacts:
  - image: relibank/accounts-service
    context: accounts_service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: relibank/transaction-service
    context: transaction_service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: relibank/bill-pay-service
    context: bill_pay
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: relibank/notifications-service
    context: notifications_service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: relibank/scheduler-service
    context: event_scheduler
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  tagPolicy:
    sha256: {}

# Default deployment configuration
deploy:
  kubectl:
    manifests:
    - k8s/namespace.yaml
    - k8s/configmap.yaml
    - k8s/secrets.yaml
    - k8s/infrastructure/*.yaml
    - k8s/databases/*.yaml
    - k8s/services/*.yaml
    hooks:
      before:
      - host:
          command: ["./k8s/manage-config.sh", "show"]
          dir: "."
      after:
      - host:
          command: ["kubectl", "wait", "--for=condition=Ready", "pods", "-l", "tier=infrastructure", "-n", "relibank", "--timeout=300s"]
          dir: "."
      - host:
          command: ["kubectl", "wait", "--for=condition=Ready", "pods", "-l", "tier=database", "-n", "relibank", "--timeout=300s"]
          dir: "."

# Port forwarding configuration
portForward:
- resourceType: service
  resourceName: accounts-service
  namespace: relibank
  port: 5000
  localPort: 5002
- resourceType: service
  resourceName: transaction-service
  namespace: relibank
  port: 5000
  localPort: 5001
- resourceType: service
  resourceName: bill-pay-service
  namespace: relibank
  port: 5000
  localPort: 5000
- resourceType: service
  resourceName: notifications-service
  namespace: relibank
  port: 5000
  localPort: 5003

# Multiple profiles for different environments and use cases
profiles:
# ===========================================
# LOCAL DEVELOPMENT PROFILE
# ===========================================
- name: local
  build:
    local:
      push: false
      useDockerCLI: true
    tagPolicy:
      envTemplate:
        template: "{{.IMAGE_NAME}}:local-{{.SHA}}"
  deploy:
    kubectl:
      manifests:
      - k8s/namespace.yaml
      - k8s/configmap.yaml
      - k8s/secrets.yaml
      - k8s/infrastructure/*.yaml
      - k8s/databases/*.yaml
      - k8s/services/*.yaml
      flags:
        global: ["--context=minikube"]
      hooks:
        before:
        - host:
            command: ["minikube", "start", "--driver=docker", "--cpus=4", "--memory=8192"]
            dir: "."
        - host:
            command: ["minikube", "addons", "enable", "ingress"]
            dir: "."
        - host:
            command: ["./k8s/manage-config.sh", "show"]
            dir: "."
        after:
        - host:
            command: ["kubectl", "wait", "--for=condition=Ready", "pods", "-l", "tier=infrastructure", "-n", "relibank", "--timeout=300s"]
            dir: "."
  activation:
  - env: SKAFFOLD_PROFILE=local

# ===========================================
# CHAOS TESTING PROFILE
# ===========================================
- name: chaos
  build:
    local:
      push: false
  deploy:
    helm:
      releases:
      - name: chaos-mesh
        remoteChart: chaos-mesh
        repo: https://charts.chaos-mesh.org
        namespace: chaos-system
        createNamespace: true
        version: "2.7.2"
        setValues:
          chaosDaemon.runtime: containerd
          chaosDaemon.socketPath: /run/containerd/containerd.sock
          dashboard.securityMode: false
          dashboard.create: true
          controllerManager.replicaCount: 1
        wait: true
    kubectl:
      manifests:
      - k8s/namespace.yaml
      - k8s/configmap.yaml
      - k8s/secrets.yaml
      - k8s/infrastructure/*.yaml
      - k8s/databases/*.yaml
      - k8s/services/*.yaml
      - chaos_mesh/experiments/*.yaml
      hooks:
        before:
        - host:
            command: ["minikube", "start", "--driver=docker", "--cpus=4", "--memory=8192"]
            dir: "."
        - host:
            command: ["minikube", "addons", "enable", "ingress"]
            dir: "."
        after:
        - host:
            command: ["kubectl", "wait", "--for=condition=Ready", "pods", "-l", "app.kubernetes.io/name=chaos-mesh", "-n", "chaos-system", "--timeout=300s"]
            dir: "."
        - host:
            command: ["echo", "🔬 Chaos Mesh installed! Dashboard: http://localhost:2333"]
            dir: "."
  activation:
  - command: chaos
