apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: relibank

build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
  artifacts:
  - image: accounts-service
    context: accounts_service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: transaction-service
    context: transaction_service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: bill-pay-service
    context: bill_pay
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: notifications-service
    context: notifications_service
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: scheduler-service
    context: event_scheduler
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "**/*.py"
        dest: /app
  - image: mssql-custom
    context: transaction_service/mssql
    docker:
      dockerfile: Dockerfile
  - image: postgres-custom
    context: accounts_service/postgres
    docker:
      dockerfile: Dockerfile

# Manifests configuration - use Kustomize to handle image name mapping and resources
manifests:
  kustomize:
    paths:
    - "k8s"

deploy:
  kubectl:
    hooks:
      before:
      - host:
          command: ["echo", "🚀 Starting Relibank deployment with Kustomize"]
          dir: "."
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
  logs:
    prefix: auto

# Port forwarding configuration - standardized for maintainability
portForward:
- resourceType: service
  resourceName: accounts-service
  namespace: relibank
  port: 5002
  localPort: 5002
- resourceType: service
  resourceName: transaction-service
  namespace: relibank
  port: 5001
  localPort: 5001
- resourceType: service
  resourceName: bill-pay-service
  namespace: relibank
  port: 5000
  localPort: 5000
- resourceType: service
  resourceName: notifications-service
  namespace: relibank
  port: 5003
  localPort: 5003
- resourceType: service
  resourceName: scheduler-service
  namespace: relibank
  port: 5004
  localPort: 5004

# Multiple profiles for different environments and use cases
profiles:
# ===========================================
# LOCAL DEVELOPMENT PROFILE
# ===========================================
- name: local
  build:
    local:
      push: false
  deploy:
    kubectl: {}
