apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bill-pay-service
  name: bill-pay-service
  namespace: relibank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill-pay-service
  template:
    metadata:
      labels:
        app: bill-pay-service
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER
                  name: infrastructure-config
            - name: TRANSACTION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: TRANSACTION_SERVICE_URL
                  name: infrastructure-config
          image: bill-pay-service
          name: bill-pay-service
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bill-pay-service
  name: bill-pay-service
  namespace: relibank
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: bill-pay-service