apiVersion: v1
kind: Service
metadata:
  labels:
    app: transaction-service
  name: transaction-service
  namespace: relibank
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5000
  selector:
    app: transaction-service
