apiVersion: v1
kind: Secret
metadata:
  name: accounts-db-credentials
  namespace: relibank
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cGFzc3dvcmQ=  # password (base64 encoded)
