apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace relibank --out k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    app: accounts-db
  name: accounts-db
  namespace: relibank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: accountsdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: accounts-db-credentials
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: accounts-db-credentials
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: postgres:15
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          name: accounts-db
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      restartPolicy: Always
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: accounts-data
