apiVersion: v1
kind: Secret
metadata:
  name: accounts-db-credentials
  namespace: relibank
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: your_password

