apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: accounts-data
  name: accounts-data
  namespace: relibank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
