apiVersion: v1
kind: ConfigMap
metadata:
  name: relibank-config
  namespace: relibank
data:
  # Database configuration (from environment variables)
  DB_HOST: "accounts-db.relibank.svc.cluster.local"
  DB_NAME: "${DB_NAME}"
  DB_USER: "${DB_USER}"

  # SQL Server configuration (from environment variables)
  DB_SERVER: "mssql.relibank.svc.cluster.local"
  DB_DATABASE: "${DB_DATABASE}"
  DB_USERNAME: "${DB_USERNAME}"

  # Kafka configuration (from environment variables)
  KAFKA_HOST: "kafka.relibank.svc.cluster.local"
  KAFKA_PORT: "${KAFKA_PORT}"
  KAFKA_INTERNAL_BROKER: "kafka.relibank.svc.cluster.local:${KAFKA_INTERNAL_PORT}"
  KAFKA_EXTERNAL_BROKER: "kafka.relibank.svc.cluster.local:${KAFKA_EXTERNAL_PORT}"

  # Service URLs
  TRANSACTION_SERVICE_URL: "http://transaction-service.relibank.svc.cluster.local:5000"
  ACCOUNTS_SERVICE_URL: "http://accounts-service.relibank.svc.cluster.local:5000"
