apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaos-dashboard-ingress
  namespace: chaos-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: chaos.relibank.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chaos-dashboard
            port:
              number: 2333
  - host: localhost
    http:
      paths:
      - path: /chaos
        pathType: Prefix
        backend:
          service:
            name: chaos-dashboard
            port:
              number: 2333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relibank-ingress
  namespace: relibank
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: nginx
  rules:
  - host: relibank.local
    http:
      paths:
      - path: /accounts(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: accounts-service
            port:
              number: 5000
      - path: /transactions(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: transaction-service
            port:
              number: 5000
      - path: /bill-pay(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bill-pay-service
            port:
              number: 5000
      - path: /notifications(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: notifications-service
            port:
              number: 5000
      - path: /scheduler(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: scheduler-service
            port:
              number: 8080
  - host: localhost
    http:
      paths:
      - path: /api/accounts(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: accounts-service
            port:
              number: 5000
      - path: /api/transactions(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: transaction-service
            port:
              number: 5000
      - path: /api/bill-pay(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bill-pay-service
            port:
              number: 5000
      - path: /api/notifications(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: notifications-service
            port:
              number: 5000
