apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: relibank

resources:
# Namespace
- namespaces/relibank-namespace.yaml

# Secrets and ConfigMaps
- secrets/mssql-secret.yaml
- secrets/accounts-db-credentials-secret.yaml
- configmaps/database-config.yaml

# Persistent Volume Claims
- storage/accounts-data-persistentvolumeclaim.yaml
- storage/mssql-data-persistentvolumeclaim.yaml

# Database Deployments
- databases/accounts-db-deployment.yaml
- databases/accounts-db-service.yaml
- databases/postgres-init-deployment.yaml
- databases/mssql-deployment.yaml
- databases/mssql-init-deployment.yaml

# Application Services
- services/accounts-service-deployment.yaml
- services/accounts-service-service.yaml
- services/bill-pay-service-deployment.yaml
- services/bill-pay-service-service.yaml
- services/notifications-service-deployment.yaml
- services/notifications-service-service.yaml
- services/scheduler-service-deployment.yaml
- services/scheduler-service-service.yaml
- services/transaction-service-deployment.yaml
- services/transaction-service-service.yaml

# Infrastructure (Kafka/Zookeeper)
- infrastructure/zookeeper-deployment.yaml
- infrastructure/zookeeper-service.yaml
- infrastructure/kafka-deployment.yaml
- infrastructure/kafka-service.yaml
