apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: relibank

resources:
# Namespace
- relibank-namespace.yaml

# Secrets and ConfigMaps
- mssql-secret.yaml
- accounts-db-credentials-secret.yaml
- accounts-db-cm1-configmap.yaml
- mssql-init-cm0-configmap.yaml

# Persistent Volume Claims
- accounts-data-persistentvolumeclaim.yaml
- mssql-data-persistentvolumeclaim.yaml

# Database Deployments
- accounts-db-deployment.yaml
- accounts-db-service.yaml
- mssql-deployment.yaml
- mssql-service.yaml
- mssql-init-deployment.yaml

# Application Services
- accounts-service-deployment.yaml
- accounts-service-service.yaml
- bill-pay-service-deployment.yaml
- bill-pay-service-service.yaml
- notifications-service-deployment.yaml
- notifications-service-service.yaml
- scheduler-service-deployment.yaml
- scheduler-service-service.yaml
- transaction-service-deployment.yaml
- transaction-service-service.yaml

# Kafka/Zookeeper
- zookeeper-deployment.yaml
- zookeeper-service.yaml
- kafka-deployment.yaml
- kafka-service.yaml
