apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: relibank-services
  namespace: relibank
  labels:
    app.kubernetes.io/name: relibank
spec:
  selector:
    matchLabels:
      tier: application
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  - port: http
    path: /health
    interval: 15s
    scrapeTimeout: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: relibank-databases
  namespace: relibank
  labels:
    app.kubernetes.io/name: relibank
spec:
  selector:
    matchLabels:
      tier: database
  endpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: relibank-kafka
  namespace: relibank
  labels:
    app.kubernetes.io/name: relibank
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: jmx
    interval: 30s
    scrapeTimeout: 10s

