apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: relibank
  labels:
    app: mssql
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
    name: tcpsql
