apiVersion: v1
kind: ResourceQuota
metadata:
  name: relibank-resource-quota
  namespace: relibank
spec:
  hard:
    # Compute Resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi

    # Storage Resources
    requests.storage: 100Gi
    persistentvolumeclaims: "10"

    # Object Count Quotas
    pods: "50"
    replicationcontrollers: "20"
    secrets: "20"
    configmaps: "20"
    services: "20"
    services.loadbalancers: "2"
    services.nodeports: "10"

    # Extended Resources
    count/deployments.apps: "20"
    count/replicasets.apps: "20"
    count/statefulsets.apps: "5"
    count/jobs.batch: "10"
    count/cronjobs.batch: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: relibank-limit-range
  namespace: relibank
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 50m
      memory: 64Mi
    type: Container
  - max:
      storage: 20Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim

