apiVersion: v1
kind: Secret
metadata:
  name: relibank-secrets
  namespace: relibank
type: Opaque
data:
  # ===========================================
  # CENTRALIZED RELIBANK SECRETS
  # All sensitive environment variables (base64 encoded)
  # ===========================================

  # ========== DATABASE PASSWORDS ==========
  # PostgreSQL password for accounts-service (base64: your_password)
  DB_PASSWORD: eW91cl9wYXNzd29yZA==

  # MSSQL SA password for transaction-service & scheduler (base64: YourStrong@Password!)
  SA_PASSWORD: WW91clN0cm9uZ0BQYXNzd29yZCE=

  # ========== AZURE COMMUNICATION SERVICES ==========
  # Azure Communication Services connection string (base64 encoded)
  AZURE_ACS_CONNECTION_STRING: ""

  # ========== THIRD-PARTY INTEGRATIONS ==========
  # Twilio credentials (commented out - add when needed)
  # TWILIO_ACCOUNT_SID: ""
  # TWILIO_AUTH_TOKEN: ""
  # TWILIO_PHONE_NUMBER: ""

  # SendGrid credentials (commented out - add when needed)
  # SENDGRID_API_KEY: ""
  # SENDGRID_SENDER_EMAIL: ""

  # ========== API KEYS & TOKENS ==========
  # Add any additional API keys or tokens here
  # JWT_SECRET_KEY: ""
  # ENCRYPTION_KEY: ""

stringData:
  # ===========================================
  # PLAIN TEXT SECRETS (for easier management)
  # These will be automatically base64 encoded
  # ===========================================

  # Example: Uncomment and set actual values
  # DB_PASSWORD_PLAIN: "your_password"
  # SA_PASSWORD_PLAIN: "YourStrong@Password!"
  # AZURE_ACS_CONNECTION_STRING_PLAIN: "endpoint=https://..."

---
# Additional secret for environment-specific overrides
apiVersion: v1
kind: Secret
metadata:
  name: relibank-secrets-env
  namespace: relibank
  labels:
    environment: "local"
type: Opaque
stringData:
  # Environment-specific overrides
  # Use this for different values per environment (dev/staging/prod)
  ENVIRONMENT_OVERRIDE: "local-development"
