/**
 * ReliBank Brute Force Attack Synthetic - Charlie Account
 * This script simulates a brute force attack attempting to login to Charlie's account
 * with multiple incorrect passwords to generate FailedLoginInvalidPassword errors in New Relic
 *
 * Documentation: https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/writing-scripted-browsers
 */

var assert = require('assert');

// Simulated brute force password attempts - expanded rainbow table
const passwordAttempts = [
  // Common passwords
  'password123',
  'Password123!',
  'password',
  'Password1',
  'pass123',
  '123456789',
  '12345678',
  '1234567890',
  'qwerty123',
  'qwertyuiop',
  'abc123',
  'monkey123',
  'letmein123',
  'letmein',
  'welcome123',
  'welcome',
  'admin123',
  'admin',
  'administrator',
  'root',

  // Charlie-specific attempts
  'charlie123',
  'Charlie123',
  'Charlie2024!',
  'charlie2024',
  'charlie@2024',
  'charlieb',
  'charlie.b',
  'charliebaker',
  'CharlieB2024',
  'charlie@relibank',

  // Bank-related attempts
  'relibank123',
  'Relibank123',
  'relibank2024',
  'banking123',
  'bank123',
  'finance123',

  // Common patterns
  'P@ssw0rd',
  'P@ssword123',
  'Password!',
  'Pass@word1',
  'Passw0rd!',
  'Summer2024',
  'Winter2024',
  'Spring2024',
  'Fall2024',

  // Keyboard patterns
  'qazwsx123',
  'qweasd123',
  'zxcvbnm123',
  'asdfgh123',
  'zaq1xsw2',

  // Dates and numbers
  '01011990',
  '12345',
  '111111',
  '000000',
  '123123',
  '121212',
  '102030',
  '2024',
  '2023',
  '2025',
  'Fall2024'
];

// Main async function
(async function() {
  try {
    console.log('=== SIMULATED BRUTE FORCE ATTACK ON CHARLIE\'S ACCOUNT ===');
    console.log('Target: charlie.b@relibank.com');
    console.log('Attempts: ' + passwordAttempts.length);
    console.log('');

    // Navigate to ReliBank login page once
    await $browser.get('http://relibank.westus2.cloudapp.azure.com/');
    console.log('Navigated to login page');

    // Wait for React to fully render
    await $browser.sleep(10000);

    // Find and fill username field once (using NAME attribute since ID is dynamically generated by MUI Autocomplete)
    const usernameField = await $browser.findElement($driver.By.name('username'));
    // Click to focus, select all with Ctrl+A, then type to replace
    await usernameField.click();
    await $browser.sleep(300);
    await usernameField.sendKeys($driver.Key.chord($driver.Key.CONTROL, 'a'));
    await $browser.sleep(200);
    await usernameField.sendKeys('charlie.b@relibank.com');
    await $browser.sleep(500);
    console.log('Username set to: charlie.b@relibank.com');
    console.log('');

    let attemptNumber = 0;

    for (const password of passwordAttempts) {
      attemptNumber++;
      console.log(`--- Attempt ${attemptNumber}/${passwordAttempts.length} ---`);

      // Find and set password field using select-all + type (ensures React state updates)
      const passwordField = await $browser.findElement($driver.By.id('password'));
      await passwordField.click();
      await $browser.sleep(300);
      await passwordField.sendKeys($driver.Key.chord($driver.Key.CONTROL, 'a'));
      await $browser.sleep(200);
      await passwordField.sendKeys(password);
      await $browser.sleep(300);
      console.log('Password attempt: ' + password);

      // Click submit button
      const submitButton = await $browser.findElement($driver.By.id('login-submit-btn'));
      await submitButton.click();
      console.log('Submitted login attempt via form');

      // Wait for response
      await $browser.sleep(3000);

      // Check if login failed (still on login page, not on dashboard)
      const url = await $browser.getCurrentUrl();
      if (!url.includes('dashboard')) {
        console.log(`✓ Attempt ${attemptNumber} failed as expected`);
      } else {
        console.log(`⚠ Attempt ${attemptNumber} succeeded (unexpected!)`);
      }

      // Delay between attempts to mimic realistic brute force attack timing
      console.log('Waiting 2.5 seconds before next attempt...');
      await $browser.sleep(2500);
      console.log('');
    }

    console.log('=== BRUTE FORCE ATTACK COMPLETE ===');
    console.log(`Total attempts: ${attemptNumber}`);

    // Final wait to ensure all telemetry is sent to New Relic
    console.log('Final wait of 5 seconds for all error telemetry to be sent to New Relic...');
    await $browser.sleep(5000);
    console.log('Browser closed. Script finished.');

  } catch (error) {
    console.error('Brute force synthetic encountered error:', error);
    throw error;
  }
})();
