apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts-db
  name: accounts-db
  namespace: relibank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: accountsdb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-credentials
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: database-credentials
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: postgres:15
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          name: accounts-db
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      restartPolicy: Always
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: accounts-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accounts-db
  name: accounts-db
  namespace: relibank
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: accounts-db
  type: ClusterIP

