apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: relibank
  labels:
    app: mssql
spec:
  serviceName: "mssql"
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mssql-custom
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_ENABLE_HADR
          value: "1"
        - name: MSSQL_AGENT_ENABLED
          value: "1"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: MSSQL_SA_PASSWORD
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: mssql
          mountPath: "/var/opt/mssql"
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: mssql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-0
  namespace: relibank
  labels:
    app: mssql
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcpsql
