apiVersion: v1
kind: ConfigMap
metadata:
  name: relibank-config
  namespace: relibank
data:
  # Production environment overrides
  ENVIRONMENT: "production"
  LOG_LEVEL: "WARN"
  DEBUG: "false"

  # Production-specific resource settings
  DEFAULT_CPU_REQUEST: "500m"
  DEFAULT_CPU_LIMIT: "1000m"
  DEFAULT_MEMORY_REQUEST: "512Mi"
  DEFAULT_MEMORY_LIMIT: "1Gi"

  # Database configuration - PostgreSQL for accounts
  DB_HOST: "accounts-db.relibank.svc.cluster.local"
  DB_NAME: "accountsdb"
  DB_USER: "postgres"

  # MSSQL configuration for transactions
  DB_SERVER: "mssql.relibank.svc.cluster.local"
  DB_DATABASE: "RelibankDB"
  DB_USERNAME: "SA"
  DB_PORT: "1433"

  # Kafka configuration with HA setup
  KAFKA_HOST: "kafka.relibank.svc.cluster.local"
  KAFKA_PORT: "9092"
  KAFKA_INTERNAL_PORT: "9092"
  KAFKA_EXTERNAL_PORT: "9094"
  KAFKA_INTERNAL_BROKER: "kafka.relibank.svc.cluster.local:9092"
  KAFKA_EXTERNAL_BROKER: "kafka.relibank.svc.cluster.local:9094"

  # Service URLs
  TRANSACTION_SERVICE_URL: "http://transaction-service.relibank.svc.cluster.local:5000"
  ACCOUNTS_SERVICE_URL: "http://accounts-service.relibank.svc.cluster.local:5000"

  # Production-specific configurations
  CACHE_TTL: "3600"
  CONNECTION_POOL_SIZE: "20"
  MAX_RETRIES: "3"
  CIRCUIT_BREAKER_ENABLED: "true"
