apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources
resources:
- ../../namespace.yaml
- ../../configmap.yaml
- ../../secrets.yaml
- ../../infrastructure/kafka.yaml
- ../../databases/databases.yaml
- ../../services/relibank-services.yaml
- ../../resource-quotas.yaml
- ../../network-policies.yaml
- ../../pod-disruption-budgets.yaml

# Production environment customizations
patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: relibank-config
- path: resource-limits-patch.yaml

# Add production-specific labels
labels:
- pairs:
    environment: production
    managed-by: helm

# Add production annotations
commonAnnotations:
  deployment.env: production
  monitoring: enabled
  backup: enabled

# Image configurations for production (use specific versions)
images:
- name: relibank/accounts-service
  newTag: v1.0.0
- name: relibank/transaction-service
  newTag: v1.0.0
- name: relibank/bill-pay-service
  newTag: v1.0.0
- name: relibank/notifications-service
  newTag: v1.0.0
- name: relibank/scheduler-service
  newTag: v1.0.0

# Replicas for production
replicas:
- name: accounts-service
  count: 5
- name: transaction-service
  count: 5
- name: bill-pay-service
  count: 3
