apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: relibank
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: accounts-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: relibank
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: transaction-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-pay-service
  namespace: relibank
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: bill-pay-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: relibank
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: notifications-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: mssql
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "8000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"

