apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: accounts-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: transaction-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-pay-service
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: bill-pay-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

