apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --namespace relibank --out k8s/
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: accounts-service
  name: accounts-service
  namespace: relibank
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5000
  selector:
    io.kompose.service: accounts-service
