apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: relibank
  labels:
    app: accounts-service
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5000
  selector:
    app: accounts-service
