apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: relibank
  labels:
    app: accounts-service
    component: backend
    part-of: relibank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
        component: backend
        part-of: relibank
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: POSTGRES_SERVER_NAME
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: POSTGRES_DATABASE_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accounts-db-credentials
                  key: password
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: POSTGRES_USER
          image: accounts-service
          name: accounts-service
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
