apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: relibank
  labels:
    app: notifications-service
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5000
  selector:
    app: notifications-service
