apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: relibank
  labels:
    app: accounts-service
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-service
  template:
    metadata:
      labels:
        app: accounts-service
        tier: application
        chaos-mesh.org/inject: enabled
    spec:
      containers:
      - name: accounts-service
        image: relibank/accounts-service
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: relibank-secrets
              key: DB_PASSWORD
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_INTERNAL_BROKER
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: relibank
  labels:
    app: accounts-service
spec:
  selector:
    app: accounts-service
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: relibank
  labels:
    app: transaction-service
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
        tier: application
        chaos-mesh.org/inject: enabled
    spec:
      containers:
      - name: transaction-service
        image: relibank/transaction-service
        ports:
        - containerPort: 5000
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_SERVER
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: relibank-secrets
              key: SA_PASSWORD
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_INTERNAL_BROKER
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: relibank
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-pay-service
  namespace: relibank
  labels:
    app: bill-pay-service
    tier: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bill-pay-service
  template:
    metadata:
      labels:
        app: bill-pay-service
        tier: application
        chaos-mesh.org/inject: enabled
    spec:
      containers:
      - name: bill-pay-service
        image: relibank/bill-pay-service
        ports:
        - containerPort: 5000
        env:
        - name: TRANSACTION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: TRANSACTION_SERVICE_URL
        - name: ACCOUNTS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: ACCOUNTS_SERVICE_URL
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_INTERNAL_BROKER
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bill-pay-service
  namespace: relibank
  labels:
    app: bill-pay-service
spec:
  selector:
    app: bill-pay-service
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: relibank
  labels:
    app: notifications-service
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
        tier: application
        chaos-mesh.org/inject: enabled
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for Kafka to be ready..."
          until nc -z $KAFKA_HOST $KAFKA_PORT; do
            echo "Kafka not ready at $KAFKA_HOST:$KAFKA_PORT, waiting 5 seconds..."
            sleep 5
          done
          echo "Kafka is ready at $KAFKA_HOST:$KAFKA_PORT!"
        env:
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_HOST
        - name: KAFKA_PORT
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_PORT
      containers:
      - name: notifications-service
        image: relibank/notifications-service
        ports:
        - containerPort: 5000
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_INTERNAL_BROKER
        - name: AZURE_ACS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: relibank-secrets
              key: AZURE_ACS_CONNECTION_STRING
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: relibank
  labels:
    app: notifications-service
spec:
  selector:
    app: notifications-service
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
  namespace: relibank
  labels:
    app: scheduler-service
    tier: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
        tier: application
        chaos-mesh.org/inject: enabled
    spec:
      containers:
      - name: scheduler-service
        image: relibank/scheduler-service
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_SERVER
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: relibank-secrets
              key: SA_PASSWORD
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: relibank-config
              key: KAFKA_INTERNAL_BROKER
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: relibank
  labels:
    app: scheduler-service
spec:
  selector:
    app: scheduler-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
