apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: relibank
  labels:
    app: scheduler-service
spec:
  ports:
    - name: "5004"
      port: 5004
      targetPort: 5000
  selector:
    app: scheduler-service
