apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-service
  namespace: relibank
  labels:
    app: scheduler-service
    component: backend
    part-of: relibank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-service
  template:
    metadata:
      labels:
        app: scheduler-service
        component: backend
        part-of: relibank
    spec:
      containers:
        - args:
            - python
            - scheduler_service.py
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: KAFKA_BROKER
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: MSSQL_SERVER_NAME
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: MSSQL_DATABASE_NAME
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: infrastructure-config
                  key: MSSQL_SA_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: MSSQL_SA_PASSWORD
          image: scheduler-service
          name: scheduler-service
      restartPolicy: Always
