apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: relibank
  labels:
    app: transaction-service
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5000
  selector:
    app: transaction-service
