apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-assistant-config
  namespace: relibank
data:
  assistant-a-id: "asst_kCFt9Bl38P4MsDac3ExgvlzK"
  assistant-b-id: "asst_lEIo99iALZ4myawLkTtaagrb"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-openai-secrets
  namespace: relibank
type: Opaque
stringData:
  endpoint: "https://eastus.api.cognitive.microsoft.com/"
  api-key: "a8be72ce0fe64c4d8a1386042a935c19"
