apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - scenario-runner-rbac.yaml
  # - relibank-ingress.yaml

patches:
  - path: persistentvolumeclaim-patch.yaml

images:
- name: accounts-service
  newTag: latest
- name: transaction-service
  newTag: latest
- name: bill-pay-service
  newTag: latest
- name: notifications-service
  newTag: latest
- name: scheduler-service
  newTag: latest
- name: scenario-runner-service
  newTag: latest
- name: chatbot-service
  newTag: latest
- name: postgres-custom
  newTag: latest
- name: mssql-custom
  newTag: latest
- name: kafka-with-monitoring
  newTag: latest
