apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources
resources:
- ../../namespace.yaml
- ../../configmap.yaml
- ../../secrets.yaml
- ../../infrastructure
- ../../databases
- ../../services

# Development environment customizations
patchesStrategicMerge:
- configmap-patch.yaml
- resource-limits-patch.yaml

# Add development-specific labels
commonLabels:
  environment: dev
  managed-by: skaffold

# Add development annotations
commonAnnotations:
  deployment.env: development
  skaffold.dev/run-id: "dev"

# Image tag suffix for development
images:
- name: relibank/accounts-service
  newTag: dev
- name: relibank/transaction-service
  newTag: dev
- name: relibank/bill-pay-service
  newTag: dev
- name: relibank/notifications-service
  newTag: dev
- name: relibank/scheduler-service
  newTag: dev
