apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources - referencing specific files to avoid circular dependency
resources:
- ../../namespace.yaml
- ../../configmap.yaml
- ../../secrets-values.yaml
- ../../infrastructure/kafka.yaml
- ../../databases/databases.yaml
- ../../services/relibank-services.yaml

# Development environment customizations
patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: relibank-config
- path: resource-limits-patch.yaml

# Add development-specific labels
labels:
- pairs:
    environment: dev
    managed-by: skaffold

# Add development annotations
commonAnnotations:
  deployment.env: development

# Image configurations for development
images:
- name: relibank/accounts-service
  newTag: dev
- name: relibank/transaction-service
  newTag: dev
- name: relibank/bill-pay-service
  newTag: dev
- name: relibank/notifications-service
  newTag: dev
- name: relibank/scheduler-service
  newTag: dev
