apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources
resources:
- ../../namespace.yaml
- ../../configmap.yaml
- ../../secrets.yaml
- ../../infrastructure
- ../../databases
- ../../services

# Staging environment customizations (using current syntax)
patches:
- path: configmap-patch.yaml
- path: resource-limits-patch.yaml

# Add staging-specific labels (using current syntax)
labels:
- pairs:
    environment: staging
    managed-by: skaffold

# Add staging annotations
commonAnnotations:
  deployment.env: staging
  skaffold.dev/run-id: "staging"

# Image tag for staging
images:
- name: relibank/accounts-service
  newTag: staging
- name: relibank/transaction-service
  newTag: staging
- name: relibank/bill-pay-service
  newTag: staging
- name: relibank/notifications-service
  newTag: staging
- name: relibank/scheduler-service
  newTag: staging

# Staging-specific replicas
replicas:
- name: accounts-service
  count: 2
- name: transaction-service
  count: 2
- name: bill-pay-service
  count: 2
