apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mssql-data
  name: mssql-data
  namespace: relibank
spec:
  storageClassName: azure-disk
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-data
  namespace: relibank
  labels:
    app: accounts-db
spec:
  storageClassName: azure-disk
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-disk
  resources:
    requests:
      storage: 2Gi
