apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service
  namespace: relibank
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: accounts-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: relibank
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: transaction-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-pay-service
  namespace: relibank
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: bill-pay-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: mssql
        resources:
          requests:
            memory: "6Gi"
            cpu: "2000m"
          limits:
            memory: "12Gi"
            cpu: "4"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
  namespace: relibank
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

